# Generated by Django 3.2.5 on 2021-07-30 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('parent', models.IntegerField()),
                ('author', models.CharField(blank=True, max_length=32, null=True)),
                ('level', models.IntegerField()),
                ('text', models.TextField()),
                ('artcle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testAPI.article')),
            ],
        ),
    ]
